version: '2'
services:
  db:
    image: postgres:17
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo18@2024
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo18:
    build: .
    image: odoo18-custom:latest
    user: root
    depends_on:
      - db
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    ports:
      - "8069:8069"
      - "11018:8069"
    tty: true
    env_file:
      - .env
    environment:
      - PIP_BREAK_SYSTEM_PACKAGES=1
      - DEV_MODE=1
      - LIST_DB=1
      - AUTO_UPDATE=p2p_bridge
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - odoo-data:/var/lib/odoo
      # Mount for development - auto-reload
      - ./addons:/opt/odoo/addons
      - ./etc/odoo.conf:/etc/odoo/odoo.conf
      # Use baked entrypoint from image to avoid CRLF or mount issues
    restart: always             # run as a service

  nginx:
    image: nginx:alpine
    depends_on:
      - odoo18
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "18069:8069"
    restart: unless-stopped

volumes:
  odoo-data:
    